@startuml
'https://plantuml.com/use-case-diagram

User -> (Регистрация пользователя)
User --> (Просмотр свободных номеров)

Customer --> (Авторизация)
Customer --> (Просмотр свободных номеров)
Customer --> (Заселение в номер)
Customer --> (Выселение из номера)
Customer --> (Добавление дополнительной услуги)
Customer --> (Оплата по счету)
Customer --> (Просмотр заказанных услуг)

(Авторизация) <--- Manager
(Просмотр свободных номеров) <--- Manager
(Заселение в номер) <--- Manager
(Выселение из номера) <--- Manager
(Добавление дополнительной услуги) <--- Manager
(Выставление счета) <-- Manager
(Добавление нового номера) <-- Manager
(Добавление/удаление услуги) <- Manager
(Изменение цены на номер) <- Manager
(Изменение цены на услугу) <- Manager
(Изменение статуса комнаты на ремонтируемую) <-- Manager
(Оплата по счету) .. (Выставление счета)


@enduml